### PR TITLE
Revamp web infrastructure

### LINKED ISSUE #332: Redo the web pages with jekyll instead of the dynamic stuff
The web pages use various DHTML/JS to avoid duplicate code (such  as menu, head content, etc.). This leads to various problems with the documentation, which needs to be included via an iframe. Code was added to compensate for this with more JS, but it's flaky.

The main reason for this was to keep dependencies to a minimum (i.e. avoid tying it to some particular hosting method), but it ended up adding more work in the way of undecipherable JS soltions.

We should move to jekyll and make use of includes to avoid duplication. Jekyll is the underlying renderer for github pages, but can also be run separately for dev/testing purposes, so it should be fine as a long term solution even outside of github. Furthermore, migration to a similar templating engine should be less difficult from Jekyll than moving from the current DHTML solution.

### PR DESCRIPTION
**Pull request by hategan**
Fixed #332

### CODE REVIEW

**Review by andre-merzky — APPROVED** [review]
I don't really feel qualified to review the code in this PR, this is not my area of expertise.  But I followed the README instructions, fought my aging system for 30 min and got it to run.  What can I say:  it looks clean and functional, so I have nothing to complain about...
Thanks!

**Comment by mturilli** [comment]
This fails with python 3.11 due to `cannot import name 'getargspec' from 'inspect'`

**Review by mturilli — COMMENTED** [review]
I tried this on MacOS that uses Python 3.11 from brew. I get the 'usual' failure ```cannot import name 'getargspec' from 'inspect'```

**Comment by hategan** [comment]
> I tried this on MacOS that uses Python 3.11 from brew. I get the 'usual' failure `cannot import name 'getargspec' from 'inspect'`

Do you have a full stack trace? This does not seem particularly related to this PR.

**Comment by mturilli** [comment]
> > I tried this on MacOS that uses Python 3.11 from brew. I get the 'usual' failure `cannot import name 'getargspec' from 'inspect'`
> 
> Do you have a full stack trace? This does not seem particularly related to this PR.

```Running Sphinx v4.5.0
/Users/mturilli/GitHub/projects/psij-python/src/
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
OUTPUT PATH = /Users/mturilli/GitHub/projects/psij-python/docs/.generated
Creating file /Users/mturilli/GitHub/projects/psij-python/docs/.generated/psij.rst.
Creating file /Users/mturilli/GitHub/projects/psij-python/docs/.generated/psij.executors.rst.
Creating file /Users/mturilli/GitHub/projects/psij-python/docs/.generated/psij.executors.batch.rst.
Creating file /Users/mturilli/GitHub/projects/psij-python/docs/.generated/psij.launchers.rst.
Creating file /Users/mturilli/GitHub/projects/psij-python/docs/.generated/psij.launchers.scripts.rst.
Creating file /Users/mturilli/GitHub/projects/psij-python/docs/.generated/modules.rst.
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 8 source files that are out of date
updating environment: [new config] 14 added, 0 changed, 0 removed
reading sources... [100%] user_guide

Warning, treated as error:
autodoc: failed to import module 'rp' from module 'psij.executors'; the following exception was raised:
cannot import name 'getargspec' from 'inspect' (/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py)
make: *** [web-docs] Error 2```

In Python 3.11, they changed `getfullargspec` with `getargspec`.

**Comment by mturilli** [comment]
As expected, with Python 3.9, compilation succeed. Maybe you want to specify that the Python version needs to be <.11?

```Running Sphinx v4.5.0
/Users/mturilli/GitHub/projects/psij-python/src/
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
OUTPUT PATH = /Users/mturilli/GitHub/projects/psij-python/docs/.generated
Creating file /Users/mturilli/GitHub/projects/psij-python/docs/.generated/psij.rst.
Creating file /Users/mturilli/GitHub/projects/psij-python/docs/.generated/psij.executors.rst.
Creating file /Users/mturilli/GitHub/projects/psij-python/docs/.generated/psij.executors.batch.rst.
Creating file /Users/mturilli/GitHub/projects/psij-python/docs/.generated/psij.launchers.rst.
Creating file /Users/mturilli/GitHub/projects/psij-python/docs/.generated/psij.launchers.scripts.rst.
Creating file /Users/mturilli/GitHub/projects/psij-python/docs/.generated/modules.rst.
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 8 source files that are out of date
updating environment: [new config] 14 added, 0 changed, 0 removed
reading sources... [100%] user_guide
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] user_guide
generating indices... genindex py-modindex done
highlighting module code... [100%] psij.utils
writing additional pages... search done
copying images... [100%] states.png
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.```

**Comment by mturilli** [comment]
Note `web/serve.sh` in https://github.com/ExaWorks/psij-python/blob/revamp_web_infrastructure/web/README.md does not seem to exist.

**Comment by andre-merzky** [comment]
> I tried this on MacOS that uses Python 3.11 from brew. I get the 'usual' failure cannot import name 'getargspec' from 'inspect'

`getargspec` apparently has been deprecated since quite a while - 3.11 forces to use `getfullargspec` instead.  Since that is available since 3.0, a change to `getfullargspec` is safe - but that returns a different set of values so some care is needed to make sure the code extracts the right ones.  [source](https://docs.python.org/3.6/library/inspect.html#inspect.getargspec)

**Comment by hategan** [comment]
@mturilli, I updated README-dev.md with proper instructions to serve the web site and docs. Do you mind taking a look, please?

**Review by mturilli — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
