### PR TITLE
Pin typeguard version to 2.xx.

### LINKED ISSUE #362: Typeguard 3.0 removes check_argument_types
... which breaks PSI/J.

They say "use the typechecked decorator", but I believe we were using check_argument_types because we could have it in an assert line which could be disabled by users when python is invoked with `-O`.

### PR DESCRIPTION
**Pull request by hategan**
Also pins filelock and psutil to known working major versions.

Fixes #362

### CODE REVIEW

**Comment by hategan** [comment]
I'm merging this without review as an emergency measure because, without it, the code is mostly unusable and because actions, such as web site deployment, fail.

**Comment by hategan** [comment]
A second set of eyes would still be useful here though.

**Review by andre-merzky — COMMENTED** [review]
Ack on the pin for typeguard.  I also don't mind the version pin on filelock and psutil, but what is the rationale?  Do you consider pinned versions more reliable / reproducible / stable in general?

**Comment by hategan** [comment]
> Ack on the pin for typeguard. I also don't mind the version pin on filelock and psutil, but what is the rationale? Do you consider pinned versions more reliable / reproducible / stable in general?

I'm trying to avoid the same problem happening in the future with filelock and psutil and I think "compatible version" (i.e. ~=) is a reasonable solution that still allows security/stability updates.

**Pull request merged**
