### PR TITLE
Old versions (<2.0) of git don't have `git remote get-url`. This uses

### LINKED ISSUE #306: Failing tests
After updating the repo:

psij-python]$ ./psij-ci-run
```
From https://github.com/ExaWorks/psij-python
 * branch            HEAD       -> FETCH_HEAD
Reading configuration... OK
error: Unknown subcommand: get-url
usage: git remote [-v | --verbose]
   or: git remote add [-t <branch>] [-m <master>] [-f] [--tags|--no-tags] [--mirror=<fetch|push>] <name> <url>
   or: git remote rename <old> <new>
   or: git remote remove <name>
   or: git remote set-head <name> (-a | -d | <branch>)
   or: git remote [-v | --verbose] show [-n] <name>
   or: git remote prune [-n | --dry-run] <name>
   or: git remote [-v | --verbose] update [-p | --prune] [(<group> | <remote>)...]
   or: git remote set-branches [--add] <name> <branch>...
   or: git remote set-url [--push] <name> <newurl> [<oldurl>]
   or: git remote set-url --add <name> <newurl>
   or: git remote set-url --delete <name> <url>

    -v, --verbose         be verbose; must be placed before a subcommand


Traceback (most recent call last):
  File "tests/ci_runner.py", line 243, in <module>
    update_origin()
  File "tests/ci_runner.py", line 199, in update_origin
    old_url = run('git', 'remote', 'get-url', 'origin')
  File "tests/ci_runner.py", line 58, in run
    raise subprocess.CalledProcessError(p.returncode, args, output=p.stdout)
subprocess.CalledProcessError: Command '('git', 'remote', 'get-url', 'origin')' returned non-zero exit status 129.
```

### PR DESCRIPTION
**Pull request by hategan**
an different way of getting the same information which is hopefully more widely supported.

Fixes #306.

### CODE REVIEW

**Review by andre-merzky — APPROVED** [review]
LGTM.  Where did you find that old git version??  Wait, I don't really want to know ... :-P

**Comment by hategan** [comment]
> Where did you find that old git version

@wilke?

**Comment by wilke** [comment]
> > Where did you find that old git version
> 
> Some place where testing failed :)

**Review by wilke — APPROVED** [review]
Looks good to me.

**Pull request merged**
