### PR TITLE
Catch SIGCHLD to figure out when a child process completes instead of

### PR DESCRIPTION
**Pull request by hategan**
polling at fixed intervals of 0.2s. Without it, `/bin/sleep 0` would take a minimum of 0.2s to complete, which is unnecessary. With the change, the same takes 0.013s instead. Still too much if you ask me.

### CODE REVIEW

**Comment by hategan** [comment]
Well, bummer. I'm getting a `RuntimeError: release unlocked lock` from `threading.Condition`:

```python
for waiter in waiters_to_notify:
           waiter.release()
```

This makes no sense since it indicates that there is a waiting thread that somehow isn't holding the cvar lock, except that `cvar.wait()` is inside a `with cvar:`.

I found this, https://bugs.python.org/issue34486, which is a 5 year old open issue, but suggests an issue with signal handling and locking in python.

So this is becoming a draft until we sort this out.

**Comment by andre-merzky** [comment]
Ah, it seems you found the bottomless pit of python signal handling...

**Comment by andre-merzky** [comment]
Ah, it seems you found the bottomless pit of python signal handling...   

I basically gave up on signalling in Python, back then when I looked at it it was broken all over the place with open tickets reaching back to 2008.  I just checked that ticket list I curated back then: some of the tickets are marked `resolved` (without further explanation though), but many still remain open, and I thus would consider signaling still broken in Python as long as *anything* from the `threading` module is used in the same code.

Ok, maybe I should try to be constructive...  The only way I can see this working would be to create a new child *process* which does not do any threading but which has wait's on a queue for spawn requests, spawns those processes, and waits on the queue again.  It also would have a signal handler which forwards any signal events on a different queue.  That way the parent process can outsource all process spawning and signal handling to that child and would get notifications about any cought `SIGCHLD` events via messages on the second queue.

But that is obviously adding complexity, makes the process tree somewhat non-intuitive, makes it harder to recover from failure etc etc. :-/

**Comment by hategan** [comment]
It's annoying because I can't reproduce it on my laptop.

**Comment by andre-merzky** [comment]
> It's annoying because I can't reproduce it on my laptop.

Is that possibly a newer Python version - maybe some fixes *did* make it into the Python releases at some point?

**Comment by hategan** [comment]
> > It's annoying because I can't reproduce it on my laptop.
> 
> Is that possibly a newer Python version - maybe some fixes _did_ make it into the Python releases at some point?

3.6, so probably not. I can't even reproduce it any more in the github workflows.

**Comment by hategan** [comment]
I added a try/catch around the issue since, even when that exception occurs, it things are seemingly no worse than without this PR (although read caveat in the comment around that catch block).

So maybe we should give this a try.

**Review by andre-merzky — APPROVED** [review]
LGTM!

**Pull request merged**
