### PR TITLE
There is no need to escape values here since the script generator alr…

### LINKED ISSUE #423: The `environment` kwarg in `JobSpec` gets the wrong number of quotation marks if there are spaces
The following behavior was observed on v0.9.0 and 79309dcc2a4079233517810c5b1c60421a8a969a.

When the `environment` kwarg of `JobSpec` has spaces in the value of the key-value pair, the resulting environment variable gets the wrong number of quotation marks.
 
```python
from psij import Job, JobAttributes, JobExecutor, JobSpec, ResourceSpecV1

job_executor = JobExecutor.get_instance("slurm")
job = Job(
    JobSpec(
        name="test",
        environment={"QUACC_VASP_PARALLEL_CMD": "srun -N 1 --ntasks-per-node=48 --cpu_bind=cores"},
        executable="/bin/date",
        resources=ResourceSpecV1(node_count = 1),
        attributes=JobAttributes(project_name = 'matgen', custom_attributes = {'slurm.constraint': 'cpu', 'slurm.qos': 'debug'}),
        launcher="single",
    )
)

job_executor.submit(job)
```

The above example produces the following Slurm script:

```bash
#!/bin/bash



#SBATCH --export=ALL

#SBATCH --exclusive

#SBATCH --nodes=1





#SBATCH --time=0:10:00


#SBATCH --account="matgen"


#SBATCH --constraint="cpu"
#SBATCH --qos="debug"


#SBATCH -e /dev/null
#SBATCH -o /dev/null

#SBATCH --export=QUACC_VASP_PARALLEL_CMD=''"'"'srun -N 1 --ntasks-per-node=48 --cpu_bind=cores'"'"''

exec &>> "/global/homes/r/rosen/.psij/work/slurm/$SLURM_JOB_ID.out"

/bin/bash /global/homes/r/rosen/.psij/work/f65b111560da52a6d41f52a732be0faf4914eb6d7af2230a8de326017979e684/single_launch.sh a0ac935e-5f34-42dc-97a7-703674b23624 '' '' '' /dev/null /dev/null /dev/null /bin/date

echo "$?" > "/global/homes/r/rosen/.psij/work/slurm/$SLURM_JOB_ID.ec"
```

Note the `#SBATCH --export` line. It's not just cumbersome --- it actually does change the meaning of the string because it goes from being

```python
"srun -N 1 --ntasks-per-node=48 --cpu_bind=cores"
```

to

```python
"'srun -N 1 --ntasks-per-node=48 --cpu_bind=cores'"
```

Doing string operations on this variable can then lead to some unexpected behavior.

This bug is not observed if you just do `environment={"hello": "world"}`.

### PR DESCRIPTION
**Pull request by hategan**
…eady does it.

Fixes #423

### CODE REVIEW

**Review by andre-merzky — APPROVED** [review]
nice catch!

**Comment by Andrew-S-Rosen** [comment]
Hi @andre-merzky! Any chance we can get this merged into `main` soon? I think if `main` is merged back into this branch, the tests should hopefully pass!

**Comment by hategan** [comment]
> Hi @andre-merzky, @hategan! Any chance we can get this merged into `main` soon? I think if the branch is updated to contain the changes in `main`, the tests should hopefully pass!

I'm not quite sure why this wasn't merged. I'll merge and make a new release.

**Comment by Andrew-S-Rosen** [comment]
@hategan: Huge thanks!! That'll be a big help :)

**Comment by hategan** [comment]
> @hategan: Huge thanks!! That'll be a big help :)

Done. 0.9.3 should be out.

**Comment by Andrew-S-Rosen** [comment]
Beautifulllll!

**Pull request merged**
