### PR TITLE
typeguard update

### LINKED ISSUE #461: Dependency on typeguard 2.12 conflicts with other packages.
At present psij-python has typeguard 2.12 as a requirement (see requirements.txt). This causes conflicts with other packages that have moved on to typeguard > 3.0.1. However the required changes seem minimal. 

Using typeguard 2.12 you would write:
```python
from typeguard import check_argument_types
...
def function(...):
    ...
    assert check_argument_types()
    ...
```
Using typeguard > 3.0.1 this becomes:
```python
from typeguard import typechecked
...
@typechecked
def function(...):
```
So far I have found 3 locations where this change needs to be made:

- src/psij/job_attributes.py
- src/psij/job_spec.py
- src/psij/resource_spec.py

Given that the require modifications seem minimal, and that the old typeguard 2.12 is incompatible with the post typeguard 3.0.1 versions, would it make sense to make these changes and update the version of typeguard that psij-python depends on?

### PR DESCRIPTION
**Pull request by andre-merzky**
This fixes #461

### CODE REVIEW

**Comment by hategan** [comment]
Annoying. @typechecked is broken.

But. It seems that if you add @typechecked to the class rather than `__init__`, mypy will not complain. I suspect it derives the type of `Cons()` using `__init__` and some heuristics.

**Comment by andre-merzky** [comment]
> Annoying. `@typechecked` is broken.
> 
> But. It seems that if you add `@typechecked` to the class rather than `__init__`, mypy will not complain. I suspect it derives the type of `Cons()` using `__init__` and some heuristics.

Yeah, it's broken.  Given that I guess that the class decorating approach is the way of least pain indeed...  Thanks!

**Comment by hategan** [comment]
For reference, `make checks` does not report any errors on my machine and tests on testing.psij.io seem to pass on this branch.

**Comment by andre-merzky** [comment]
> For reference, `make checks` does not report any errors on my machine and tests on testing.psij.io seem to pass on this branch.

Yeah, same here - tests pass fine locally, docs build all right, but github CI still complains...

**Comment by hategan** [comment]
> > For reference, `make checks` does not report any errors on my machine and tests on testing.psij.io seem to pass on this branch.
> 
> Yeah, same here - tests pass fine locally, docs build all right, but github CI still complains...

I think we can merge. If we run into issues building the docs after, we can address it then.

**Comment by hategan** [comment]
By the way, I approve of this PR :)

**Review by mtitov — APPROVED** [review]
LGTM!

**Comment by hategan** [comment]
The failing tests are due to RP installing an older version of PSI/J as a dependency, which conflicts with the version being tested. While we should address the "circular" dependency (there is little sense to use PSI/J to submit to PSI/J via RP), this needs not happen now since RP is an optional install.

**Pull request merged**
